title: Driftless Trout Fishing Trip Log
email: devroutf@gmail.com
description: >-
  This website is primarily to keep track of logs of my fishing trips. If you stumbled across the public page and also fish the Driftless, please don't share this :)
baseurl: ""
url: ""
twitter_username: devroutf
github_username: Cyro6
youtube_username: "@DeVrouTroutFishing"
youtube_url: https://www.youtube.com/channel/UC2pdP7GsKvLWVEXqHY61bnQ

logo: /assets/images/DTF_Logo.png
favicon: /assets/images/DTF_Logo.png

remote_theme: daviddarnes/alembic
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

navigation_pages:
  - about.markdown

navigation_header:
  - title: Home
    url: /
  - title: Analytics
    url: /Analytics
  - title: Map
    url: /map
  - title: Insights
    url: /insights
  - title: Planner
    url: /planner
  - title: Resources
    url: /resources
  - title: YouTube
    url: /youtube
  - title: About
    url: /about